DefaultContentLanguage = "es"
linkedin = "https://www.linkedin.com/in/jmservera/"
github = "https://github.com/jmservera"
theme = "bootstrap4-blog"
enableGitInfo = true
paginate = 5

[params]
    author = "Juan Manuel Servera"
    [params.social]
        twitter = "jmservera"
    [params.sidebar]
        about = "Un blog cualquiera"

[languages]
    [languages.es]
        languageCode = "es-es"
        languageName = "Español"
        title = "Blog-o-mático 2000"
        baseURL = "https://jmblog-es.servezas.org"
        theme = "bootstrap4-blog"
        weight = 1
    [languages.en]
        languageCode = "en-us"
        languageName = "English"
        title = "Blog-o-matic 2000"
        baseURL = "https://jmblog-en.servezas.org"
        weight = 2
