DefaultContentLanguage = "es"
baseURL = "https://jmblog.servezas.org"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
enableGitInfo = true
paginate = 30
enableRobotsTXT = true
copyright="Juan Manuel Servera"
googleAnalytics="UA-29316797-3"

staticDir = ["static","static_en"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

[params]
    author = "Juan Manuel Servera"
    twitter = "https://twitter.com/jmservera"
    github = "https://github.com/jmservera"
    linkedin = "https://linkedin.com/in/jmservera"
    stackoverflow = "https://stackoverflow.com/users/107102/jmservera"
    featured_image = "/images/1500x500.jfif"    
    show_reading_time = true
    tags = ["Azure", "DevOps", "AI"]
    background_color_class = "bg-black"
    recent_posts_number = 5

[markup.goldmark.renderer]
    unsafe= true

[languages]
    [languages.es]
        languageCode = "es-es"
        languageName = "Español"
        title = "Dev-o-Mático 2000"
        weight = 1
    [languages.en]
        languageCode = "en-us"
        languageName = "English"
        title = "Dev-o-Matic 2000"
        weight = 2
        staticDir2 = "static_en"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false