DefaultContentLanguage = "es"
baseURL = "https://jmblog.servezas.org"
theme = "ananke"
enableGitInfo = true
paginate = 5
enableRobotsTXT = true
copyright="Juan Manuel Servera"
googleAnalytics="UA-29316797-3"

staticDir = ["static","static_en"]

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

[params]
    author = "Juan Manuel Servera"
    twitter = "https://twitter.com/jmservera"
    github = "https://github.com/jmservera"
    linkedin = "https://linkedin.com/in/jmservera"
    stackoverflow = "https://stackoverflow.com/users/107102/jmservera"
    featured_image = "/images/1500x500.jfif"    

[languages]
    [languages.es]
        languageCode = "es-es"
        languageName = "Español"
        title = "Dev-o-Mático 2000"
        theme = "bootstrap4-blog"
        weight = 1
    [languages.en]
        languageCode = "en-us"
        languageName = "English"
        title = "Dev-o-Matic 2000"
        weight = 2
        staticDir2 = "static_en"