DefaultContentLanguage = "es"
baseURL = "https://jmblg.servezas.org"
linkedin = "https://www.linkedin.com/in/jmservera/"
github = "https://github.com/jmservera"
theme = "ananke"
enableGitInfo = true
paginate = 5
enableRobotsTXT = true

staticDir = ["static","static_en"]

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

[params]
    author = "Juan Manuel Servera"
    twitter = "https://twitter.com/jmservera"
    github = "https://github.com/jmservera"
    linkedin = "https://linkedin.com/in/jmservera"
    stackoverflow = "https://stackoverflow.com/users/107102/jmservera"
    featured_image = "/images/1500x500.jfif"

[languages]
    [languages.es]
        languageCode = "es-es"
        languageName = "Español"
        title = "Blog-o-mático 2000"
        theme = "bootstrap4-blog"
        weight = 1
    [languages.en]
        languageCode = "en-us"
        languageName = "English"
        title = "Blog-o-matic 2000"
        weight = 2
        staticDir2 = "static_en"